name: Checker

on:
  issues:
    types: [opened, reopened]

jobs:
  hw-checker:
    runs-on: ubuntu-22.04
    premissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Cache pip
        uses: actions/cache@v4
        id: pip-cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies if not hit cache
        if: steps.pip-cache.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Answer
        uses: zhangt2333/action-judger@main
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          USERNAME: ${{ github.event.issue.user.login }}
        with:
          script: |
            python main.py
